### ISSUE TITLE
Date Péremption

### ISSUE THREAD

**Issue by Carlos8191970** [PAMCollegeShawinigan/Hippie#102]
Actuellement, si un produit ne requiert aucune date de péremption, on pousse la date du jour par défaut.
Peut-être prévoir un mécanisme pour mettre l'enregistrement dans la base de données à "null" pour s'assurer qu'il n'y ait aucune date de péremption.
Dans la classe AjoutMarchandiseActivity.java

**Comment by BleuShan** [comment]
Réglé, on pousse la date quand même, mais le serveur devrait assigner la date à null si le type est non périssable.
