### ISSUE TITLE
Sérialisation des id en json du côté serveur.

### ISSUE THREAD

**Issue by BleuShan** [PAMCollegeShawinigan/Hippie#71]
Les nom des valeurs en json ne sont pas consistent principalement sur les ID des objets.

http://www.yolainecourteau.com/hippie/laravel/public/utilisateur retourne par exemple:
[{"utilisateur_id":"4","nom":"Lachance","prenom":"Pier-Alain"},{"utilisateur_id":"5","nom":"test","prenom":"test"},{"utilisateur_id":"6","nom":"Gratton","prenom":"Bob"}]

au lieu de:

[{"id":"4","nom":"Lachance","prenom":"Pier-Alain"},{"id":"5","nom":"test","prenom":"test"},{"id":"6","nom":"Gratton","prenom":"Bob"}]

et 

http://www.yolainecourteau.com/hippie/laravel/public/utilisateur/{id} retourne par exemple:

{"nom":"test","prenom":"test","courriel":"test@test.com","telephone":"123-456-7890","organisme":{"organisme_id":"4","nom_organisme":"Organisme_4"}}

ou lieu de:
{"nom":"test","prenom":"test","courriel":"test@test.com","telephone":"123-456-7890","organisme":{"id":"4","nom_organisme":"Organisme_4"}}

**Comment by pieralainlachance** [comment]
C'est réglé
