### ISSUE TITLE
Le serveur sur alimentaire/ajout répond avec un 500 sur une requête qui semble correcte

### ISSUE THREAD

**Issue by BleuShan** [PAMCollegeShawinigan/Hippie#72]
Une requête post avec tout les champs remplit de la façon suivante:

description_alimentaire: test
nom: Postman Test
quantite: 253
type_alimentaire: 1
marchandise_unite: 3
marchandise_etat: 3
donneur_id: 4
valeur: 33
date_peremption: 1450648972

Réponse provenant du serveur:

PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens.

Le client Android est répondu de la manière.

Mon impression c'est que c'est c'est du à une parenthèse non fermée à la ligne 56  du fichier alimentaire.php

**Comment by pieralainlachance** [comment]
La parenthèse a été ajouté un test est de mise

**Comment by pieralainlachance** [comment]
Le probleme venait d'une variable sql mal appelé j'avais oublié  un deux point (:) et une parenthèse un autre test serait de mise

**Comment by BleuShan** [comment]
Ça fonctionne. :+1:
